# Generated by Django 4.0.3 on 2022-04-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=50)),
                ('city', models.TextField(max_length=40)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
