# Generated by Django 4.0.3 on 2022-04-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='postal',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
