# Generated by Django 4.0.3 on 2022-04-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userinfo_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='about',
            field=models.TextField(default='about', max_length=200),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='postal',
            field=models.IntegerField(default=0),
        ),
    ]
