# Generated by Django 4.0.3 on 2022-04-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userinfo_about_alter_userinfo_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='sid',
            field=models.IntegerField(default=9999),
        ),
    ]
