# Generated by Django 4.0.3 on 2022-04-10 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loginfo',
        ),
    ]
