# Generated by Django 4.0.3 on 2022-04-10 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_loginfo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loginfo',
            table=None,
        ),
    ]
