# Generated by Django 4.0.3 on 2022-04-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_loginfo_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginfo',
            name='sid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
