# Generated by Django 4.0.3 on 2022-04-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_dashinfo_graphres_delete_loginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashinfo',
            name='due',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashinfo',
            name='others',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashinfo',
            name='paid',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashinfo',
            name='payable',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphres',
            name='fall22',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphres',
            name='spring22',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
