# Generated by Django 4.0.3 on 2022-04-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=20)),
                ('reg', models.CharField(max_length=20)),
                ('mid', models.CharField(max_length=20)),
                ('fin', models.CharField(max_length=20)),
            ],
        ),
    ]
